replicaCount: 3
image:
  repository: ganeshnimmakayala/jenkinsci
  tag: 1
  pullPolicy: IfNotPresent
container:
  port: 80
service:
  type: LoadBalancer
  port: 8082
  targetPort: 80
ingress:
  enabled: false
