replicaCount: 3
image:
  repository: ganeshnimmakayala/jenkinsci
  tag: "3"
  pullPolicy: IfNotPresent
container:
  port: 80
service:
  type: LoadBalancer
  port: 80
  targetPort: 8082
ingress:
  enabled: false
