replicaCount: 3

image:
  repository: ganeshnimmakayala/jenkinsci
  tag: latest
  pullPolicy: IfNotPresent

container:
  port: 80

service:
  type: Nodeport
  port: 80
  targetPort: 80
  nodeport: 30002
ingress:
  enabled: false

