replicaCount: 3

image:
  repository: ganeshnimmakayala/jenkinsci
  tag: latest
  pullPolicy: IfNotPresent

container:
  port: 80

service:
  type: LoadBalancer
  port: 80
  targetPort: 80
ingress:
  enabled: false

